import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
// const jJellycow = localfont({
//   variable: "--font-jJellycow",
//   src: "/font/jJellycow.ttf",
//   subsets: ["latin"],
// });
export const metadata: Metadata = {
  title: "Create",
  description: "Generated by create next app",
  openGraph: {
    title: "Home",
    description: "A next js app with TanStack Query ",
    siteName: "Next.js App",
    images:
      "https://i.pinimg.com/736x/40/ca/42/40ca4256ac9f5842f0dc9bee54a24af5.jpg",
    locale:"en_US",
    type:"website",
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
